name: Deploy Minecraft Server with Fabric 1.20.1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # Usa la versión de Java que necesites

      - name: Download Fabric Server
        run: |
          # Descarga el instalador de Fabric
          curl -OJ https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.11.2/fabric-installer-0.11.2.jar
          
          # Ejecuta el instalador de Fabric para la versión de Minecraft 1.20.1
          java -jar fabric-installer-0.11.2.jar server -mcversion 1.20.1 -downloadMinecraft

      - name: Accept EULA
        run: echo "eula=true" > eula.txt

      - name: Create Necessary Folders
        run: |
          mkdir -p mods  # Carpeta para mods
          mkdir -p config  # Carpeta para configuraciones de mods
          mkdir -p world  # Carpeta para los archivos del mundo
          mkdir -p logs  # Carpeta para archivos de registro
          mkdir -p crash-reports  # Carpeta para informes de errores
          mkdir -p backups  # Carpeta para respaldos

      - name: Configure Server Properties
        run: |
          echo "server-ip=pebetes.ddns.net" >> server.properties
          echo "server-port=25565" >> server.properties
          echo "motd=A Fabric Minecraft Server on GitHub Actions" >> server.properties

      - name: Start Minecraft Server with Fabric
        run: |
          java -Xmx8G -Xms4G -jar fabric-server-launch.jar nogui
